const APP_DATA = {
  title: "Destroying The Works Of The Devil Through Prayer",
  subtitle: "The Book of Luke - Interactive Course NT3",
  author: "Leonard N. Cheeseborough",
  
  greaterWorks: `John 14:12 — "Verily, verily, I say unto you, He that believeth on me, the works that I do shall he do also; and greater works than these shall he do; because I go unto my Father."`,
  greaterWorksAffirmation: "I CAN DO THE GREATER WORKS IN JESUS NAME",

  preTest: {
    title: "Pre-Test: Prior Knowledge",
    instruction: "Take the pre-test to determine your prior knowledge of each passage. Use your imagination to sketch or write your knowledge about each passage without using any resources. The post test will be taken after completing the Destroying the Works of the Devil Workbook to measure what you have learned.",
    days: [
      { day: 1, passage: "Luke 4:18-19" },
      { day: 2, passage: "Luke 4:40-42" },
      { day: 3, passage: "Luke 5:12-15" },
      { day: 4, passage: "Luke 17:11-19" },
      { day: 5, passage: "Luke 8:43-48" },
      { day: 6, passage: "Luke 18:35-43" },
      { day: 7, passage: "Luke 6:6-10" },
      { day: 8, passage: "Luke 7:2-10" },
      { day: 9, passage: "Luke 5:16-26" },
      { day: 10, passage: "Luke 11:21-23" },
      { day: 11, passage: "Luke 11:24-26" },
      { day: 12, passage: "Luke 4:33-36" },
      { day: 13, passage: "Luke 4:38-39" },
      { day: 14, passage: "Luke 8:26-40" },
      { day: 15, passage: "Luke 9:38-42" },
      { day: 16, passage: "Luke 11:14-20" },
      { day: 17, passage: "Luke 8:1-2" },
      { day: 18, passage: "Luke 13:11-17" },
      { day: 19, passage: "Luke 14:2-5" },
      { day: 20, passage: "Luke 7:11-17" },
      { day: 21, passage: "Luke 8:41-42; 8:49-56" },
      { day: 22, passage: "Luke 7:18-23" },
      { day: 23, passage: "Luke 13:32-33" },
      { day: 24, passage: "Luke 11:1-4" },
      { day: 25, passage: "Luke 11:9-13" },
      { day: 26, passage: "Luke 11:5-8" },
      { day: 27, passage: "Luke 18:1-8" },
      { day: 28, passage: "Luke 18:9-14" },
      { day: 29, passage: "Luke 9:1-9" },
      { day: 30, passage: "Luke 9:49-50" },
      { day: 31, passage: "Luke 10:17-20" },
      { day: 32, passage: "Luke 10:25-37" }
    ]
  },

  postTest: {
    title: "Post-Test of the Book of Luke",
    instruction: "Now that you have completed the Destroying the Works of the Devil Workbook, take the post-test to measure what you have learned. Use your imagination to sketch or write your knowledge about each passage.",
    days: [
      { day: 1, passage: "Luke 4:18-19" },
      { day: 2, passage: "Luke 4:40-42" },
      { day: 3, passage: "Luke 5:12-15" },
      { day: 4, passage: "Luke 17:11-19" },
      { day: 5, passage: "Luke 8:43-48" },
      { day: 6, passage: "Luke 18:35-43" },
      { day: 7, passage: "Luke 6:6-10" },
      { day: 8, passage: "Luke 7:2-10" },
      { day: 9, passage: "Luke 5:16-26" },
      { day: 10, passage: "Luke 11:21-23" },
      { day: 11, passage: "Luke 11:24-26" },
      { day: 12, passage: "Luke 4:33-36" },
      { day: 13, passage: "Luke 4:38-39" },
      { day: 14, passage: "Luke 8:26-40" },
      { day: 15, passage: "Luke 9:38-42" },
      { day: 16, passage: "Luke 11:14-20" },
      { day: 17, passage: "Luke 8:1-2" },
      { day: 18, passage: "Luke 13:11-17" },
      { day: 19, passage: "Luke 14:2-5" },
      { day: 20, passage: "Luke 7:11-17" },
      { day: 21, passage: "Luke 8:41-42; 8:49-56" },
      { day: 22, passage: "Luke 7:18-23" },
      { day: 23, passage: "Luke 13:32-33" },
      { day: 24, passage: "Luke 11:1-4" },
      { day: 25, passage: "Luke 11:9-13" },
      { day: 26, passage: "Luke 11:5-8" },
      { day: 27, passage: "Luke 18:1-8" },
      { day: 28, passage: "Luke 18:9-14" },
      { day: 29, passage: "Luke 9:1-9" },
      { day: 30, passage: "Luke 9:49-50" },
      { day: 31, passage: "Luke 10:17-20" },
      { day: 32, passage: "Luke 10:25-37" }
    ]
  },

  chapters: [
    {
      id: 1,
      title: "Christ's Ministry",
      image: null,
      lessons: [1, 2],
      lessonThemes: ["Luke 4:18-19 — Jesus began his ministry.", "Luke 4:40-42 — Christ laid his hands on everyone."],
      reviewHeadings: ["Jesus began his ministry.", "Jesus laid hands on everyone."],
      reviewScriptures: `Luke 4:18 — "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised..."\n\nMatthew 8:16-17 — "When the even was come, they brought unto him many that were possessed with devils: and he cast out the spirits with his word, and healed all that were sick: That it might be fulfilled which was spoken by Esaias the prophet, saying, Himself took our infirmities, and bare our sicknesses."`,
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 1 "Christ's Ministry" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 2,
      title: "Be Thou Clean",
      image: null,
      lessons: [3, 4],
      lessonThemes: ["Luke 5:12-15 — I will, be thou clean.", "Luke 17:11-19 — Ten men healed of Leprosy."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 2 "Be Thou Clean" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 3,
      title: "Believe In Your Heart",
      image: null,
      lessons: [5, 6],
      lessonThemes: ["Luke 8:43-48 — Your faith has made you whole.", "Luke 18:35-43 — Jesus heals a blind beggar."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 3 "Believe in your heart" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 4,
      title: "Doctrine (Say in a Word)",
      image: null,
      lessons: [7, 8],
      lessonThemes: ["Luke 6:6-10 — Stretch forth thy hand.", "Luke 7:2-10 — Say in a Word."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 4 "The Doctrine (Say in a Word)" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 5,
      title: "Destroying the Works of the Devil",
      image: null,
      lessons: [9, 10, 11],
      lessonThemes: ["Luke 5:16-26 — The Power of the Lord was Present to Heal.", "Luke 11:21-23 — First, bind the strong man.", "Luke 11:24-26 — The return of the evil spirit."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 5 "Destroying the Works of the Devil" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 6,
      title: "Manifestation of the Works of the Devil - Part 1",
      image: null,
      lessons: [12, 13, 14, 15, 16],
      lessonThemes: ["Luke 4:33-36 — Hold your peace and come out.", "Luke 4:38-39 — Fever, Come out.", "Luke 8:26-40 — Commanded the unclean spirit to come out.", "Luke 9:38-42 — Jesus Rebuked the Unclean Spirit.", "Luke 11:14-20 — Jesus casting out a dumb devil."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 6 "Manifestation of the Works of the Devil Part 1" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 7,
      title: "Manifestation of the Works of the Devil - Part 2",
      image: null,
      lessons: [17, 18, 19],
      lessonThemes: ["Luke 8:1-2 — Magdalene Healed of Evil Spirits and Infirmities.", "Luke 13:10-17 — Woman, Thou art Loose from Your Infirmity.", "Luke 14:2-5 — A Man Healed from Dropsy."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 7 "Manifestation of the Works of the Devil Part 2" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 8,
      title: "Arise",
      image: null,
      lessons: [20, 21],
      lessonThemes: ["Luke 7:11-17 — Young man, I say unto you Arise.", "Luke 8:41-42; 8:49-56 — Maid, Arise."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 8 "Arise" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 9,
      title: "Go and Tell",
      image: null,
      lessons: [22, 23],
      lessonThemes: ["Luke 7:18-23 — Tell what you have seen and heard.", "Luke 13:32-33 — Tell that Fox."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 9 "Go and Tell" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 10,
      title: "Prayer",
      image: null,
      lessons: [24, 25],
      lessonThemes: ["Luke 11:1-4 — Teach us How to Pray.", "Luke 11:9-13 — Ask, Seek & Knock."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 10 "Prayer" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 11,
      title: "The Results of Prayer",
      image: null,
      lessons: [26, 27, 28],
      lessonThemes: ["Luke 11:5-8 — Arise and Give.", "Luke 18:1-8 — God will Avenge your Adversary.", "Luke 18:9-14 — True Prayers."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 11 "The Results of Prayer" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    },
    {
      id: 12,
      title: "The Power and Authority",
      image: null,
      lessons: [29, 30, 31, 32],
      lessonThemes: ["Luke 9:1-5 — Jesus gave the 12 Disciples Power and Authority.", "Luke 9:49-50 — One Casting out Devils in Jesus Name.", "Luke 10:17-20 — I give you power.", "Luke 10:30-35 — Showing mercy toward your neighbor."],
      reviewHeadings: ["", ""],
      reviewScriptures: "",
      personalApplicationPrompt: `Ask God for the understanding and application of Chapter 12 "The Power and Authority" for your personal life. List the life application(s) as the Holy Spirit reveals them.`
    }
  ],

  lessons: [
    {
      id: 1,
      chapterId: 1,
      number: 1,
      title: "Jesus Began His Ministry",
      passage: "Luke 4:18-19",
      additionalPassages: "Isaiah 61:1-3",
      theme: "Jesus began his ministry.",
      image: "color_4_18_19.jpg",
      scripture: `Luke 4:16-21 — And he came to Nazareth, where he had been brought up: and, as his custom was, he went into the synagogue on the sabbath day, and stood up for to read. And there was delivered unto him the book of the prophet Esaias. And when he had opened the book, he found the place where it was written, The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised, To preach the acceptable year of the Lord. And he closed the book, and he gave it again to the minister, and sat down. And the eyes of all them that were in the synagogue were fastened on him. And he began to say unto them, This day is this scripture fulfilled in your ears.`,
      keyTerms: [
        { word: "Nazareth", definition: "the guarded one and the ordinary residence and home town of Christ." },
        { word: "Custom", definition: "to be accustomed, used, that which is wont, as his custom was, or as his manner was." },
        { word: "Synagogue", definition: "a bringing together, gathering (as of fruits); in the NT, an assembling together of men, an assembly of Jews formally gathered together to offer prayers and listen to the reading and expositions of the scriptures." },
        { word: "Read", definition: "to distinguish between, to recognise, to know accurately, or to acknowledge." },
        { word: "Delivered", definition: "to hand, give by hand; to give over; give up to the power or will of one." },
        { word: "Book", definition: "a scroll, a written document; a sheet on which something has been written or a bill of divorcement." },
        { word: "Esaias", definition: "Jehovah's help; a famous Hebrew prophet who prophesied in the reigns of Uzziah, Jotham, Ahaz, and Hezekiah." },
        { word: "Opened", definition: "to unroll; the books of the Hebrews were rolls fastened to one or two smooth rods and furnished with handles, so that they could be rolled up and unrolled." },
        { word: "Found", definition: "to come upon, hit upon, to meet with; after searching, to find a thing sought; without previous search, to find (by chance), to fall in with." },
        { word: "Closed", definition: "to fold together, or roll up." },
        { word: "Minister", definition: "servant; an underrower, subordinate rower; any one who serves with hands, in the NT of the officers and attendants of magistrates; of the attendants of a king; of the attendant of a synagogue." },
        { word: "Fastened", definition: "to fix the eyes on, gaze upon; to look into anything or metaphorically to fix one's mind on one as an example." },
        { word: "Scripture", definition: "a writing, thing written; used to denote either the book itself, or its contents; a certain portion or section of the Holy Scripture." },
        { word: "Fulfilled", definition: "to make full, to fill up; to cause to abound, to furnish or supply liberally; to render full, to complete; fill to the brim so that nothing shall be wanting to full measure." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 4:18-19; Isaiah 61:1-3\nTheme: Jesus began his ministry.",
      questions: [
        "According to verse 16, what was Jesus' custom, and what does this reveal about His spiritual lifestyle?",
        "Where did Jesus go to read, and based on the definition of synagogue, what was the purpose of this gathering?",
        "What was delivered to Jesus, and what does this action suggest about His role and authority in the synagogue?",
        "Who is Esaias (Isaiah), and why is it significant that Jesus read from his writings?",
        "Based on the definition of 'opened' (to unroll), what does this tell you about how Scripture was handled in Jesus' time?",
        "What does the word 'found' suggest about Jesus locating the passage — was it random, or intentional? Explain your answer.",
        "Define 'read' (to recognize or acknowledge accurately). How does this deepen your understanding of Jesus reading the Scripture?",
        "In verses 18–19, list at least four things Jesus said He was anointed to do. What does this reveal about His mission?",
        "What does it mean that the eyes of the people were 'fastened' on Him (v. 20)? What does this indicate about the atmosphere in the room?",
        "In verse 21, Jesus says, 'This day is this scripture fulfilled in your ears.' What is the main point of this statement, and what is Jesus declaring about Himself?"
      ]
    },
    {
      id: 2,
      chapterId: 1,
      number: 2,
      title: "Christ Laid His Hands on Everyone and Healed Them",
      passage: "Luke 4:40-42",
      additionalPassages: "Matthew 8:16-17; Mark 1:32-34",
      theme: "Christ laid his hands on everyone and healed them.",
      image: "color_4_40_41.jpg",
      scripture: `Luke 4:40-42 — Now when the sun was setting, all they that had any sick with divers diseases brought them unto him; and he laid his hands on every one of them, and healed them. And devils also came out of many, crying out, and saying, Thou art Christ the Son of God. And he rebuking them suffered them not to speak: for they knew that he was Christ. And when it was day, he departed and went into a desert place: and the people sought him, and came unto him, and stayed him, that he should not depart from them.`,
      keyTerms: [
        { word: "All", definition: "each, every, any, the whole, everyone, all things, everything, collectively, or some of all types." },
        { word: "Sick", definition: "to be weak, feeble, to be without strength, powerless, to be weak in means, needy, or poor." },
        { word: "Divers", definition: "of various sorts or various in character." },
        { word: "Diseases", definition: "sickness, infirmity or of moral disability." },
        { word: "Brought", definition: "to lead, take with one, to lead by laying hold of, and this way to bring to the point of destination, to lead by accompanying to a place or guide, or direct." },
        { word: "Laid", definition: "to put or lay upon, to have put on, to attack one, or to make an assault on one." },
        { word: "Every", definition: "each." },
        { word: "Devils", definition: "the divine power, deity, divinity, a spirit, a being inferior to God, superior to men, evil spirits or the messengers and ministers of the devil." },
        { word: "Crying", definition: "to croak or speak with a loud voice." },
        { word: "Came", definition: "to go or come forth of or from." },
        { word: "Saying", definition: "to point out with words or to call by name." },
        { word: "Knew", definition: "to see, to perceive, notice, discern, or discover." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 4:40-42; Matthew 8:16-17; Mark 1:32-34\nTheme: Christ laid his hands on everyone and healed them.",
      questions: [
        "What kind of problems did the people have in the passages above? a) b)",
        "What two ways did Jesus heal the sick and possessed? 1) 2)",
        "How many sick did Jesus heal in the passages above?",
        "How many were set free of those that were possessed with devils?",
        "What did Jesus tell the devils not to do?",
        "What was Esaias' prophecy that was fulfilled by Jesus?",
        "Whom did the devils say about Jesus?"
      ]
    },
    {
      id: 3,
      chapterId: 2,
      number: 3,
      title: "I Will; Be Thou Clean",
      passage: "Luke 5:12-15",
      additionalPassages: "Mark 1:40-45",
      theme: "I Will; Be thou Clean.",
      image: "color_5_12_14.jpg",
      scripture: `Luke 5:12-15 — And it came to pass, when he was in a certain city, behold a man full of leprosy: who seeing Jesus fell on his face, and besought him, saying, Lord, if thou wilt, thou canst make me clean. And he put forth his hand, and touched him, saying, I will: be thou clean. And immediately the leprosy departed from him. And he charged him to tell no man: but go, and shew thyself to the priest, and offer for thy cleansing, according as Moses commanded, for a testimony unto them. But so much the more went there a fame abroad of him: and great multitudes came together to hear, and to be healed by him of their infirmities.`,
      keyTerms: [
        { word: "Certain", definition: "only one, someone." },
        { word: "City", definition: "the place in which one lives." },
        { word: "Man", definition: "with reference to sex; of a male; of a husband." },
        { word: "Leprosy", definition: "a most offensive, annoying, dangerous, cutaneous disease, the virus of which generally pervades the whole body, common in Egypt and the East." },
        { word: "Touched", definition: "to fasten one's self to, adhere to, cling to; of levitical practice of having no fellowship with heathen practices." },
        { word: "Will", definition: "to will, have in mind, intend; to be resolved or determined, to purpose; to desire, to wish; to take delight in, have pleasure." },
        { word: "Clean", definition: "to make clean, cleanse; from physical stains and dirt; to cleanse by curing; in a moral sense; to free from defilement of sin and from faults; to free from guilt of sin, to purify." },
        { word: "Immediately", definition: "straightway, immediately, forthwith." },
        { word: "Departed", definition: "to go away, depart; of departing evils and sufferings." },
        { word: "Charged", definition: "to transmit a message along from one to another, to declare, announce; to command, order." },
        { word: "Healed", definition: "to serve, do service; cure, restore to health." },
        { word: "Infirmities", definition: "want of strength, weakness, infirmity; of the body: feebleness of health or sickness; of the soul: want of strength and capacity requisite." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 5:12-15; Matthew 8:1-6; Mark 1:40-45\nTheme: I Will; Be thou Clean.",
      questions: [
        "What disease did the man have in the passage?",
        "Whom did the man see in the passage?",
        "What did the man do toward Jesus?",
        "What two ways did the leper worship Jesus? 1) 2)",
        "What did the leper say to Jesus?",
        "How did Jesus feel about the leper?",
        "What did Jesus say to the leper?",
        "How long did it take to heal the man with leprosy?",
        "Whom did Jesus tell the man that had leprosy to show himself to? Why?"
      ]
    },
    {
      id: 4,
      chapterId: 2,
      number: 4,
      title: "Ten Men Healed of Leprosy",
      passage: "Luke 17:11-19",
      additionalPassages: "",
      theme: "Ten Men healed of Leprosy.",
      image: "color_l17_11_19.jpg",
      scripture: `Luke 17:12-19 — And as he entered into a certain village, there met him ten men that were lepers, which stood afar off: And they lifted up their voices, and said, Jesus, Master, have mercy on us. And when he saw them, he said unto them, Go shew yourselves unto the priests. And it came to pass, that, as they went, they were cleansed. And one of them, when he saw that he was healed, turned back, and with a loud voice glorified God, And fell down on his face at his feet, giving him thanks: and he was a Samaritan. And Jesus answering said, Were there not ten cleansed? but where are the nine? There are not found that returned to give glory to God, save this stranger. And he said unto him, Arise, go thy way: thy faith hath made thee whole.`,
      keyTerms: [
        { word: "Entered", definition: "to go out or come in." },
        { word: "Certain", definition: "a definite one." },
        { word: "Village", definition: "the common sleeping place to which labourers in the field return." },
        { word: "Ten", definition: "the number after nine." },
        { word: "Lepers", definition: "leprous, affected with leprosy." },
        { word: "Mercy", definition: "to help one afflicted or seeking aid; to bring help to the wretched." },
        { word: "Cleansed", definition: "to make clean, cleanse; to cleanse by curing; from physical stains and dirt; to free from guilt of sin, to purify." },
        { word: "Healed", definition: "to cure, to make whole; to free from errors and sins, to bring about one's salvation." },
        { word: "Samaritan", definition: "an inhabitant of the city of Samaria." },
        { word: "Arise", definition: "to cause to rise up, raise up; of persons lying down, of persons lying on the ground." },
        { word: "Faith", definition: "conviction of the truth of anything, belief; in the NT of a conviction or belief respecting man's relationship to God and divine things." },
        { word: "Whole", definition: "to save, keep safe and sound, to rescue from danger or destruction." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 17:11-19\nTheme: Ten Men healed of Leprosy.",
      questions: [
        "What two cities did Jesus pass through the midst of while he was traveling to Jerusalem?",
        "What place did Jesus enter?",
        "Whom did Jesus meet in the village?",
        "What was Jesus' distance to the lepers?",
        "What did the ten lepers say to Jesus?",
        "What did Jesus see?",
        "What instruction did Jesus give to the lepers?",
        "What happened as they obeyed Jesus' instructions?",
        "What did one of the lepers see about himself?",
        "What did the one leper that was healed do after he was healed?",
        "The leper that returned to Jesus was from what city?",
        "What did Jesus say that made the leper whole?"
      ]
    },
    {
      id: 5,
      chapterId: 3,
      number: 5,
      title: "Your Faith Have Made You Whole",
      passage: "Luke 8:43-48",
      additionalPassages: "",
      theme: "Your faith has made you whole.",
      image: "color_8_43.jpg",
      scripture: `Luke 8:43-48 — And a woman having an issue of blood twelve years, which had spent all her living upon physicians, neither could be healed of any, Came behind him, and touched the border of his garment: and immediately her issue of blood stanched. And Jesus said, Who touched me? When all denied, Peter and they that were with him said, Master, the multitude throng thee and press thee, and sayest thou, Who touched me? And Jesus said, Somebody hath touched me: for I perceive that virtue is gone out of me. And when the woman saw that she was not hid, she came trembling, and falling down before him, she declared unto him before all the people for what cause she had touched him, and how she was healed immediately. And he said unto her, Daughter, be of good comfort: thy faith hath made thee whole; go in peace.`,
      keyTerms: [
        { word: "Woman", definition: "a female of any age, whether a virgin, or married, or a widow." },
        { word: "Issue", definition: "a flowing problem." },
        { word: "Blood", definition: "refers to the seat of life." },
        { word: "Physicians", definition: "medical doctors; Surgeons." },
        { word: "Touched", definition: "to fasten one's self to, adhere to, cling to." },
        { word: "Garment", definition: "attires, i.e. the cloak or mantle and the tunic." },
        { word: "Stanched", definition: "to stand by or near; to stop, stand still, to stand immovable, stand firm." },
        { word: "Multitude", definition: "Crowd; an assembly of men who have flocked together in some place." },
        { word: "Virtue", definition: "strength power, ability; inherent power, power residing in a thing by virtue of its nature." },
        { word: "Declared", definition: "to proclaim, to make known openly, declare." },
        { word: "Faith", definition: "conviction of the truth of anything, belief; in the NT of a conviction or belief respecting man's relationship to God and divine things." },
        { word: "Whole", definition: "to save, keep safe and sound, to rescue from danger or destruction." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 8:43-48\nTheme: Your faith has made you whole.",
      questions: [
        "What was wrong with the woman?",
        "How long had this woman been sick?",
        "Who did the woman give all her money to be healed?",
        "What did the woman touch of Jesus?",
        "What happened to the woman's blood when she touched Jesus?",
        "How long did it take for the woman to manifest her healing?",
        "How did Jesus know someone touched him?",
        "Why did the woman think she should declare that it was her that touched Jesus?",
        "What did Jesus say to his daughter?"
      ]
    },
    {
      id: 6,
      chapterId: 3,
      number: 6,
      title: "Jesus Heals a Blind Beggar",
      passage: "Luke 18:35-43",
      additionalPassages: "Matthew 20:29-34; Mark 10:46-52",
      theme: "Jesus Heals a Blind Beggar.",
      image: "color_18_35_43.jpg",
      scripture: `Luke 18:35-43 — And it came to pass, that as he was come nigh unto Jericho, a certain blind man sat by the way side begging: And hearing the multitude pass by, he asked what it meant. And they told him, that Jesus of Nazareth passeth by. And he cried, saying, Jesus, thou Son of David, have mercy on me. And they which went before rebuked him, that he should hold his peace: but he cried so much the more, Thou Son of David, have mercy on me. And Jesus stood, and commanded him to be brought unto him: and when he was come near, he asked him, Saying, What wilt thou that I shall do unto thee? And he said, Lord, that I may receive my sight. And Jesus said unto him, Receive thy sight: thy faith hath saved thee. And immediately he received his sight, and followed him, glorifying God: and all the people, when they saw it, gave praise unto God.`,
      keyTerms: [
        { word: "Blind", definition: "Sightless, visionless, unseeing." },
        { word: "Hearing", definition: "to attend to, consider what is or has been said; a thing comes to one's ears, to find out, learn." },
        { word: "Mercy", definition: "to help one afflicted or seeking aid; to help the afflicted, to bring help to the wretched." },
        { word: "Commanded", definition: "to order; directed; charged." },
        { word: "Receive", definition: "Obtain; Be given." },
        { word: "Sight", definition: "Vision, ability to see, prospect; picture, scene." },
        { word: "Faith", definition: "conviction of the truth of anything, belief; in the NT of a conviction or belief respecting man's relationship to God." },
        { word: "Saved", definition: "keep safe and sound, to rescue from danger or destruction; to preserve one who is in danger of destruction." },
        { word: "Immediately", definition: "forthwith, instantly." },
        { word: "Glorifying", definition: "to praise, extol, magnify, celebrate." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 18:35-43; Matthew 20:29-34; Mark 10:46-52\nTheme: Jesus Heals a Blind Beggar.",
      questions: [
        "Where was Jesus travelling near?",
        "Who sat by the way side?",
        "What was the man doing?",
        "What was told to the man sitting on the way side?",
        "What did the blind man say after he found that Jesus was passing by?",
        "What did Jesus command concerning the blind man?",
        "What did the blind man reply when Jesus asked what he wanted?",
        "How did Jesus heal the blind man?",
        "What did Jesus say saved him?",
        "How long did it take for the healing to manifest?"
      ]
    },
    {
      id: 7,
      chapterId: 4,
      number: 7,
      title: "Stretch Forth Thy Hand",
      passage: "Luke 6:6-10",
      additionalPassages: "Matthew 12:9-14; Mark 3:1-6",
      theme: "Stretch forth thy Hand.",
      image: "color_6_6_10.jpg",
      scripture: `Luke 6:6-10 — And it came to pass also on another sabbath, that he entered into the synagogue and taught: and there was a man whose right hand was withered. And the scribes and Pharisees watched him, whether he would heal on the sabbath day; that they might find an accusation against him. But he knew their thoughts, and said to the man which had the withered hand, Rise up, and stand forth in the midst. And he arose and stood forth. Then said Jesus unto them, I will ask you one thing; Is it lawful on the sabbath days to do good, or to do evil? to save life, or to destroy it? And looking round about upon them all, he said unto the man, Stretch forth thy hand. And he did so: and his hand was restored whole as the other.`,
      keyTerms: [
        { word: "Synagogue", definition: "a bringing together, gathering; in the NT, an assembling together of men, an assembly of Jews formally gathered together to offer prayers and listen to the reading and expositions of the scriptures." },
        { word: "Withered", definition: "Dry; of members of the body deprived of their natural juices, shrunk, wasted." },
        { word: "Thoughts", definition: "the thinking of a man deliberating with himself; a thought, inward reasoning." },
        { word: "Rise", definition: "to arouse, to cause to increase from a seat or bed." },
        { word: "Stand", definition: "to cause or make to stand, to place, put, set; to bid to stand by, in the presence of others, in the midst, before judges." },
        { word: "Stretch", definition: "Expanse, over, towards, against one." },
        { word: "Restored", definition: "to be in its former state; reinstated; reestablished." },
        { word: "Whole", definition: "sound: of a man who is sound in body." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 6:6-10; Matthew 12:9-14; Mark 3:1-6\nTheme: Stretch Forth thy Hand.",
      questions: [
        "What did Jesus enter on the Sabbath Day?",
        "What was Jesus doing before the miracle occurred?",
        "What was wrong with the man that Jesus blessed?",
        "Who was watching Jesus while he was in the Synagogue?",
        "What did Jesus know about the Scribes and Pharisees?",
        "What was the first thing that Jesus said to the man with the withered hand?",
        "What was the second thing that Jesus said to the man with the withered hand?"
      ]
    },
    {
      id: 8,
      chapterId: 4,
      number: 8,
      title: "Say in a Word",
      passage: "Luke 7:2-10",
      additionalPassages: "Matthew 8:5-13",
      theme: "Say in a Word.",
      image: "color_7_1_9.jpg",
      scripture: `Luke 7:2-10 — And a certain centurion's servant, who was dear unto him, was sick, and ready to die. And when he heard of Jesus, he sent unto him the elders of the Jews, beseeching him that he would come and heal his servant. And when they came to Jesus, they besought him instantly, saying, That he was worthy for whom he should do this: For he loveth our nation, and he hath built us a synagogue. Then Jesus went with them. And when he was now not far from the house, the centurion sent friends to him, saying unto him, Lord, trouble not thyself: for I am not worthy that thou shouldest enter under my roof: Wherefore neither thought I myself worthy to come unto thee: but say in a word, and my servant shall be healed. For I also am a man set under authority, having under me soldiers, and I say unto one, Go, and he goeth; and to another, Come, and he cometh; and to my servant, Do this, and he doeth it. When Jesus heard these things, he marvelled at him, and turned him about, and said unto the people that followed him, I say unto you, I have not found so great faith, no, not in Israel. And they that were sent, returning to the house, found the servant whole that had been sick.`,
      keyTerms: [
        { word: "Centurion", definition: "an officer in the Roman army." },
        { word: "Heard", definition: "to perceive by the ear what is announced in one's presence; a thing comes to one's ears, to find out, learn." },
        { word: "Elders", definition: "of age, advanced in life, an elder, a senior; forefathers." },
        { word: "Worthy", definition: "sufficient; many enough, enough; sufficient in ability, fit." },
        { word: "Word", definition: "uttered by a living voice, embodies a conception or idea; what someone has said; the act of speaking, speech." },
        { word: "Authority", definition: "power of choice, liberty of doing as one pleases; the power of rule or government." },
        { word: "Marveled", definition: "to wonder, wonder at, marvel; to be wondered at, to be had in admiration." },
        { word: "Faith", definition: "conviction of the truth of anything, belief." },
        { word: "Whole", definition: "to be sound, to be well, to be in good health." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 7:2-10; Matthew 8:5-13\nTheme: Say in a Word.",
      questions: [
        "What city did this event occur?",
        "What was wrong with the centurion's servant?",
        "Who did the centurion send unto Jesus?",
        "What two things did the Elders of the Jews say about the centurion?",
        "Who did the centurion send unto Jesus when he was halfway?",
        "What did the Centurion's friends say unto Jesus?",
        "What did the Centurion say about his authority?",
        "Why did Jesus marvel at the centurion?",
        "What did Jesus say to the centurion after his testimony?",
        "When was the Centurion's servant healed in this passage?"
      ]
    },
    {
      id: 9,
      chapterId: 5,
      number: 9,
      title: "The Power of the Lord was Present to Heal",
      passage: "Luke 5:16-26",
      additionalPassages: "Matthew 9:1-8; Mark 2:1-12",
      theme: "The Power of the Lord was Present to Heal them.",
      image: "color_5_16_26.jpg",
      scripture: `Luke 5:16-26 — And he withdrew himself into the wilderness, and prayed. And it came to pass on a certain day, as he was teaching, that there were Pharisees and doctors of the law sitting by, which were come out of every town of Galilee, and Judaea, and Jerusalem: and the power of the Lord was present to heal them. And, behold, men brought in a bed a man which was taken with a palsy: and they sought means to bring him in, and to lay him before him. And when they could not find by what way they might bring him in because of the multitude, they went upon the housetop, and let him down through the tiling with his couch into the midst before Jesus. And when he saw their faith, he said unto him, Man, thy sins are forgiven thee. And the scribes and the Pharisees began to reason, saying, Who is this which speaketh blasphemies? Who can forgive sins, but God alone? But when Jesus perceived their thoughts, he answering said unto them, What reason ye in your hearts? Whether is easier, to say, Thy sins be forgiven thee; or to say, Rise up and walk? But that ye may know that the Son of man hath power upon earth to forgive sins, (he said unto the sick of the palsy,) I say unto thee, Arise, and take up thy couch, and go into thine house. And immediately he rose up before them, and took up that whereon he lay, and departed to his own house, glorifying God. And they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day.`,
      keyTerms: [
        { word: "Wilderness", definition: "solitary, lonely, desolate, uninhabited; used of places; a desert; deserted places, lonely regions." },
        { word: "Prayed", definition: "to offer prayers, to pray." },
        { word: "Power", definition: "strength power, ability; inherent power, power residing in a thing by virtue of its nature; power for performing miracles." },
        { word: "Lord", definition: "he to whom a person or thing belongs, about which he has power of deciding; master, lord." },
        { word: "Present", definition: "into, unto, to, towards, for, among; current, existing." },
        { word: "Heal", definition: "to cure, to make whole, to free from errors and sins, to bring about one's salvation." },
        { word: "Palsy", definition: "to loose on one side or from the side; to loose or part things placed side by side." },
        { word: "Faith", definition: "conviction of the truth of anything, belief; in the NT of a conviction or belief respecting man's relationship to God." },
        { word: "Sins", definition: "to be without a share in; to miss the mark; to err, be mistaken." },
        { word: "Forgiven", definition: "to send away; to bid going away or depart; to let go, give up a debt, forgive, to remit." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 5:16-26; Matthew 9:1-6; Mark 2:1-12\nTheme: The Power of the Lord was Present to Heal them.",
      questions: [
        "Where did this miracle take place?",
        "Who was present with Jesus to heal the sick?",
        "Who was brought to Jesus?",
        "Who brought the man with palsy to Jesus?",
        "What did Jesus see in the men who brought the man with palsy?",
        "What was the first thing that Jesus said to the man with palsy?",
        "Where did Jesus perceive the thoughts of the scribes and the Pharisees?",
        "Where did Jesus tell the man to go?",
        "How did Jesus heal the man with palsy?",
        "What did the man do when he was healed?",
        "What three things happened to the people that witnessed the palsy man's healing?"
      ]
    },
    {
      id: 10,
      chapterId: 5,
      number: 10,
      title: "First, Bind the Strong Man",
      passage: "Luke 11:21-23",
      additionalPassages: "Matthew 12:22-30; Mark 3:22-27",
      theme: "First, Bind the Strong Man.",
      image: "color_11_20_23.jpg",
      scripture: `Luke 11:21-23 — When a strong man armed keepeth his palace, his goods are in peace: But when a stronger than he shall come upon him, and overcome him, he taketh from him all his armour wherein he trusted, and divideth his spoils. He that is not with me is against me: and he that gathereth not with me scattereth.`,
      keyTerms: [
        { word: "Strong", definition: "mighty; violent, forcibly uttered, firm, sure." },
        { word: "Armed", definition: "furnish with arms." },
        { word: "Overcome", definition: "to conquer; to carry off the victory, come off victorious." },
        { word: "Armour", definition: "full armour, complete armour; includes shield, sword, lance, helmet, greaves, and breastplate." },
        { word: "Trusted", definition: "to trust, have confidence, be confident." },
        { word: "Divideth", definition: "to distribute, divide among several; to give over, deliver." },
        { word: "Spoils", definition: "a beast's skin stripped off; the weapons and valuables stripped off from an enemy, spoils." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:21-23; Matthew 12:22-30; Mark 3:22-27\nTheme: First, Bind The Strong Man.",
      questions: [
        "Who is Jesus talking about in these passages?",
        "What are the conditions of the strong man's goods?",
        "Who can overcome the strong man?",
        "What can the stronger one do to the strong man's spoils?",
        "What did Jesus say about those that are not with him?",
        "What did Jesus say about those that are not gathering with him?",
        "What must happen first before you can enter into a strong man's house?"
      ]
    },
    {
      id: 11,
      chapterId: 5,
      number: 11,
      title: "The Return of the Evil Spirit",
      passage: "Luke 11:24-26",
      additionalPassages: "",
      theme: "The Return of the Evil Spirit.",
      image: "color_11_24_28.jpg",
      scripture: `Luke 11:24-26 — When the unclean spirit is gone out of a man, he walketh through dry places, seeking rest; and finding none, he saith, I will return unto my house whence I came out. And when he cometh, he findeth it swept and garnished. Then goeth he, and taketh to him seven other spirits more wicked than himself; and they enter in, and dwell there: and the last state of that man is worse than the first.`,
      keyTerms: [
        { word: "Unclean", definition: "not cleansed, in a moral sense: unclean in thought and life; in a ceremonial sense: that which must be abstained from according to the levitical law." },
        { word: "Spirit", definition: "the disposition or influence which fills and governs the soul of any one." },
        { word: "Walketh", definition: "to go through, pass through; to go different places." },
        { word: "Seeking", definition: "to seek in order to find; to seek a thing; to seek after, seek for, aim at, strive after." },
        { word: "Return", definition: "to turn back; to turn about; to return." },
        { word: "Seven", definition: "the number after six." },
        { word: "Wicked", definition: "more evil." },
        { word: "Dwell", definition: "settle; inhabit; metaph. divine powers, influences, etc., are said to dwell in his soul, to pervade, prompt, govern it." },
        { word: "Worse", definition: "poorer; not as good as; of poorer quality; eviler." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:24-26\nTheme: The Return of the Evil Spirit.",
      questions: [
        "What does the unclean spirit do when he is gone out of a man?",
        "What does the unclean spirit say when he finds no rest?",
        "What does the unclean spirit find when he returns?",
        "What does the unclean spirit do after finding the house empty?",
        "How many spirits does the unclean spirit bring back?",
        "What is the condition of the last state of the man?",
        "What lesson can we learn from this passage about keeping our lives filled with God?"
      ]
    },
    {
      id: 12,
      chapterId: 6,
      number: 12,
      title: "Hold Your Peace and Come Out",
      passage: "Luke 4:33-36",
      additionalPassages: "Mark 1:23-28",
      theme: "Hold your Peace and Come Out.",
      image: "color_4_31_37.jpg",
      scripture: `Luke 4:33-36 — And in the synagogue there was a man, which had a spirit of an unclean devil, and cried out with a loud voice, Saying, Let us alone; what have we to do with thee, thou Jesus of Nazareth? art thou come to destroy us? I know thee who thou art; the Holy One of God. And Jesus rebuked him, saying, Hold thy peace, and come out of him. And when the devil had thrown him in the midst, he came out of him, and hurt him not. And they were all amazed, and spake among themselves, saying, What a word is this! for with authority and power he commandeth the unclean spirits, and they come out.`,
      keyTerms: [
        { word: "Synagogue", definition: "in the NT, an assembling together of men, an assembly of Jews formally gathered together to offer prayers and listen to the reading and expositions of the scriptures." },
        { word: "Spirit", definition: "used of demons, or evil spirits, who were conceived as inhabiting the bodies of men." },
        { word: "Unclean", definition: "not cleansed, in a ceremonial sense: that which must be abstained from according to the levitical law." },
        { word: "Devil", definition: "a spirit, a being inferior to God, superior to men, evil spirits or the messengers and ministers of the devil." },
        { word: "Rebuked", definition: "to tax with fault, rate, chide, rebuke, reprove, censure severely, to admonish or charge sharply." },
        { word: "Authority", definition: "power of choice, liberty of doing as one pleases, leave or permission, physical and mental power." },
        { word: "Power", definition: "ability, inherent power, power residing in a thing by virtue of its nature." },
        { word: "Commandeth", definition: "to enjoin upon, order, command, charge." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 4:33-36; Mark 1:23-28\nTheme: Hold your Peace and Come Out.",
      questions: [
        "According to verse 16, what was Jesus' custom, and what does this reveal about His spiritual lifestyle?",
        "Where did Jesus go to read, and based on the definition of synagogue, what was the purpose of this gathering?",
        "What was delivered to Jesus, and what does this action suggest about His role and authority in the synagogue?",
        "Who is Esaias (Isaiah), and why is it significant that Jesus read from his writings?",
        "Based on the definition of 'opened' (to unroll), what does this tell you about how Scripture was handled in Jesus' time?",
        "What does the word 'found' suggest about Jesus locating the passage — was it random, or intentional? Explain your answer.",
        "Define 'read' (to recognize or acknowledge accurately). How does this deepen your understanding of Jesus reading the Scripture?",
        "In verses 18–19, list at least four things Jesus said He was anointed to do. What does this reveal about His mission?",
        "What does it mean that the eyes of the people were 'fastened' on Him (v. 20)? What does this indicate about the atmosphere in the room?",
        "In verse 21, Jesus says, 'This day is this scripture fulfilled in your ears.' What is the main point of this statement, and what is Jesus declaring about Himself?"
      ]
    },
    {
      id: 13,
      chapterId: 6,
      number: 13,
      title: "Fever, Come Out",
      passage: "Luke 4:38-39",
      additionalPassages: "Matthew 8:14-15; Mark 1:29-31",
      theme: "Fever, Come out.",
      image: "color_4_38_39.jpg",
      scripture: `Luke 4:38-39 — And he arose out of the synagogue, and entered into Simon's house. And Simon's wife's mother was taken with a great fever; and they besought him for her. And he stood over her, and rebuked the fever; and it left her: and immediately she arose and ministered unto them.`,
      keyTerms: [
        { word: "Arose", definition: "to cause to rise up, raise up; raise up from laying down." },
        { word: "Entered", definition: "to go out or come in: to enter." },
        { word: "Fever", definition: "fiery heat." },
        { word: "Besought", definition: "to question; to ask; to request, entreat, beg, beseech." },
        { word: "Stood", definition: "to stand over one, place one's self above; used especially of persons coming upon one suddenly." },
        { word: "Rebuked", definition: "to tax with fault, rate, chide, rebuke, reprove, censure severely." },
        { word: "Left", definition: "to give up, keep no longer; to leave, go away from one." },
        { word: "Immediately", definition: "forthwith, instantly; straightaway." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 4:38-39; Matthew 8:14-15; Mark 1:29-31\nTheme: Fever, Come out.",
      questions: [
        "Whose house did Jesus enter after leaving the synagogue?",
        "Whom did Jesus see when he entered the house?",
        "Peter's wife's mother was sick with what?",
        "What two ways did the Bible say that Jesus healed Peter's wife's mother? 1) 2)",
        "How long did it take for the fever to leave her?",
        "What did she do for Jesus and the others after she was healed?"
      ]
    },
    {
      id: 14,
      chapterId: 6,
      number: 14,
      title: "Commanded the Unclean Spirit to Come Out",
      passage: "Luke 8:26-40",
      additionalPassages: "Matthew 8:28-34; Mark 5:1-20",
      theme: "Commanded the unclean spirit to come out.",
      image: "color_8_26_39.jpg",
      scripture: `Luke 8:26-40 — And they arrived at the country of the Gadarenes, which is over against Galilee. And when he went forth to land, there met him out of the city a certain man, which had devils long time, and ware no clothes, neither abode in any house, but in the tombs. When he saw Jesus, he cried out, and fell down before him, and with a loud voice said, What have I to do with thee, Jesus, thou Son of God most high? I beseech thee, torment me not. (For he had commanded the unclean spirit to come out of the man. For oftentimes it had caught him: and he was kept bound with chains and in fetters; and he brake the bands, and was driven of the devil into the wilderness.) And Jesus asked him, saying, What is thy name? And he said, Legion: because many devils were entered into him. And they besought him that he would not command them to go out into the deep. And there was there an herd of many swine feeding on the mountain: and they besought him that he would suffer them to enter into them. And he suffered them. Then went the devils out of the man, and entered into the swine: and the herd ran violently down a steep place into the lake, and were choked. When they that fed them saw what was done, they fled, and went and told it in the city and in the country. Then they went out to see what was done; and came to Jesus, and found the man, out of whom the devils were departed, sitting at the feet of Jesus, clothed, and in his right mind: and they were afraid. Return to thine own house, and shew how great things God hath done unto thee.`,
      keyTerms: [
        { word: "Gadarenes", definition: "reward at the end; was the capital of Peraea, situated opposite the south extremity of the Lake of Gennesaret." },
        { word: "Devils", definition: "a spirit, a being inferior to God, superior to men, evil spirits or the messengers and ministers of the devil." },
        { word: "Torment", definition: "to test metals by the touchstone; to question by applying torture, to vex with grievous pains of body or mind." },
        { word: "Commanded", definition: "to transmit a message along from one to another, to declare, announce, order, charge." },
        { word: "Legion", definition: "a body of soldiers whose number differed at different times." },
        { word: "Swine", definition: "Pigs, Hogs, or Boars." },
        { word: "Clothed", definition: "Dressed, attired, covered, or cloaked." },
        { word: "Mind", definition: "to exercise self control, to put a moderate estimate upon one's self, think of one's self soberly." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 8:26-40; Matthew 8:28-34; Mark 5:1-20\nTheme: Commanded the Unclean Spirit to come out.",
      questions: [
        "Where did this miracle take place?",
        "Who met Jesus outside the city?",
        "What was the condition of the man?",
        "What did the man do when he saw Jesus?",
        "What did the loud voice say to Jesus?",
        "What did Jesus command the unclean spirit to do?",
        "What was the name of the unclean spirit?",
        "Where did the unclean spirit want to go?",
        "What happened to the swine?",
        "What was the man's condition after the unclean spirit was cast out?",
        "Why did the people want Jesus to depart from among them?",
        "What did Jesus say to the man who was healed from the unclean spirits?"
      ]
    },
    {
      id: 15,
      chapterId: 6,
      number: 15,
      title: "Jesus Rebuked the Unclean Spirit",
      passage: "Luke 9:38-42",
      additionalPassages: "Matthew 17:14-21; Mark 9:37-43",
      theme: "Jesus Rebuked the Unclean Spirit.",
      image: "color_9_38_42.jpg",
      scripture: `Luke 9:38-42 — And, behold, a man of the company cried out, saying, Master, I beseech thee, look upon my son: for he is mine only child. And, lo, a spirit taketh him, and he suddenly crieth out; and it teareth him that he foameth again, and bruising him hardly departeth from him. And I besought thy disciples to cast him out; and they could not. And Jesus answering said, O faithless and perverse generation, how long shall I be with you, and suffer you? Bring thy son hither. And as he was yet a coming, the devil threw him down, and tare him. And Jesus rebuked the unclean spirit, and healed the child, and delivered him again to his father.`,
      keyTerms: [
        { word: "Company", definition: "a crowd, a casual collection of people, a multitude of men who have flocked together in some place." },
        { word: "Taketh", definition: "with the hand, lay hold of, any person or thing in order to use it; to seize, to lay hold of." },
        { word: "Teareth", definition: "to convulse, tear." },
        { word: "Foameth", definition: "spraying, boiling or bubbling." },
        { word: "Bruising", definition: "break, to break in pieces, shiver, to tread down, to break down, crush, to tear one's body and shatter one's strength." },
        { word: "Cast", definition: "drive out, to send out, to expel a person from a society: to banish from a family." },
        { word: "Healed", definition: "to cure, to make whole, to free from errors and sins, to bring about one's salvation." },
        { word: "Delivered", definition: "to give away for one's own profit what is one's own; to give back, restore." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 9:38-42; Matthew 17:14-21; Mark 9:37-43\nTheme: Jesus Rebuked the unclean Spirit.",
      questions: [
        "Who came unto Jesus from among the multitude?",
        "What was the man's body position before he began to talk?",
        "What did the spirit do to the man's son?",
        "What did the father call his own son?",
        "Who could not cast out the unclean spirit in the man?",
        "What happened while the man with the spirit was coming to Jesus?",
        "What did Jesus do to the unclean spirit?",
        "How did Jesus heal the man?",
        "How long did it take the man to manifest his healing?",
        "Why could the disciples not heal the man?",
        "How did Jesus say this kind of spirit goes out?"
      ]
    },
    {
      id: 16,
      chapterId: 6,
      number: 16,
      title: "Jesus Casting Out a Dumb Devil",
      passage: "Luke 11:14-20",
      additionalPassages: "",
      theme: "Jesus casting out a dumb devil.",
      image: "color_11_14_17.jpg",
      scripture: `Luke 11:14-20 — And he was casting out a devil, and it was dumb. And it came to pass, when the devil was gone out, the dumb spake; and the people wondered. But some of them said, He casteth out devils through Beelzebub the chief of the devils. And others, tempting him, sought of him a sign from heaven. But he, knowing their thoughts, said unto them, Every kingdom divided against itself is brought to desolation; and a house divided against a house falleth. If Satan also be divided against himself, how shall his kingdom stand? because ye say that I cast out devils through Beelzebub. And if I by Beelzebub cast out devils, by whom do your sons cast them out? therefore shall they be your judges. But if I with the finger of God cast out devils, no doubt the kingdom of God is come upon you.`,
      keyTerms: [
        { word: "Dumb", definition: "silent, mute; without the faculty of speech." },
        { word: "Wondered", definition: "to wonder, admire; to be struck with admiration or astonishment." },
        { word: "Beelzebub", definition: "lord of flies; a name of Satan, the prince of evil spirits." },
        { word: "Kingdom", definition: "royal power, kingship, dominion, rule." },
        { word: "Desolation", definition: "making desolate, desolation; laying waste." },
        { word: "Divided", definition: "to divide, separate, tear asunder." },
        { word: "Finger", definition: "a finger; used metaphorically of God's power." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:14-20\nTheme: Jesus casting out a dumb devil.",
      questions: [
        "What type of devil did Jesus cast out in this passage?",
        "What happened when the devil was gone out?",
        "What did some of the people say about Jesus?",
        "What was Jesus' response to their accusation?",
        "What did Jesus say about a kingdom divided against itself?",
        "How did Jesus say He cast out devils?",
        "What did Jesus say about the kingdom of God?"
      ]
    },
    {
      id: 17,
      chapterId: 7,
      number: 17,
      title: "Magdalene Healed of Evil Spirits and Infirmities",
      passage: "Luke 8:1-2",
      additionalPassages: "",
      theme: "Magdalene Healed of Evil Spirits and Infirmities.",
      image: "color_8_1_2.jpg",
      scripture: `Luke 8:1-2 — And it came to pass afterward, that he went throughout every city and village, preaching and shewing the glad tidings of the kingdom of God: and the twelve were with him, And certain women, which had been healed of evil spirits and infirmities, Mary called Magdalene, out of whom went seven devils.`,
      keyTerms: [
        { word: "Preaching", definition: "to be a herald, to officiate as a herald; to proclaim after the manner of a herald; always with the suggestion of formality, gravity, and an authority which must be listened to and obeyed." },
        { word: "Glad tidings", definition: "to bring good news, to announce glad tidings; used in the NT of the joyful tidings of the kingdom of God." },
        { word: "Healed", definition: "to cure, to make whole; to free from errors and sins, to bring about one's salvation." },
        { word: "Evil", definition: "of a bad nature or condition; in a physical sense: diseased or blind; in an ethical sense: evil, wicked, bad." },
        { word: "Infirmities", definition: "want of strength, weakness, infirmity; feebleness of health or sickness." },
        { word: "Magdalene", definition: "of Magdala; Mary of Magdala, a woman of Galilee." },
        { word: "Devils", definition: "evil spirits or the messengers and ministers of the devil." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 8:1-2\nTheme: Magdalene Healed of Evil Spirits and Infirmities.",
      questions: [
        "Where was Jesus going in this passage?",
        "What was Jesus doing as he traveled?",
        "Who was with Jesus on his journey?",
        "Who were the certain women that followed Jesus?",
        "What had happened to the women who followed Jesus?",
        "How many devils had come out of Mary Magdalene?",
        "What does this passage teach us about who Jesus ministers to?"
      ]
    },
    {
      id: 18,
      chapterId: 7,
      number: 18,
      title: "Woman, Thou Art Loose from Your Infirmity",
      passage: "Luke 13:10-17",
      additionalPassages: "",
      theme: "Woman, Thou art Loose from Your Infirmity.",
      image: "color_13_10_14.jpg",
      scripture: `Luke 13:10-17 — And he was teaching in one of the synagogues on the sabbath. And, behold, there was a woman which had a spirit of infirmity eighteen years, and was bowed together, and could in no wise lift up herself. And when Jesus saw her, he called her to him, and said unto her, Woman, thou art loosed from thine infirmity. And he laid his hands on her: and immediately she was made straight, and glorified God. And the ruler of the synagogue answered with indignation, because that Jesus had healed on the sabbath day, and said unto the people, There are six days in which men ought to work: in them therefore come and be healed, and not on the sabbath day. The Lord then answered him, and said, Thou hypocrite, doth not each one of you on the sabbath loose his ox or his ass from the stall, and lead him away to watering? And ought not this woman, being a daughter of Abraham, whom Satan hath bound, lo, these eighteen years, be loosed from this bond on the sabbath day?`,
      keyTerms: [
        { word: "Infirmity", definition: "want of strength, weakness; feebleness of health or sickness; inability to produce results." },
        { word: "Bowed", definition: "to be completely bowed; bent together; doubled up, bent down." },
        { word: "Loosed", definition: "to loose any person or thing tied or fastened; to set free; to dismiss, to release one bound." },
        { word: "Immediately", definition: "forthwith, instantly; at once." },
        { word: "Straight", definition: "upright, erect; of persons rising; metaph. straight, i.e. upright, true." },
        { word: "Indignation", definition: "excited against, indignant." },
        { word: "Hypocrite", definition: "one who answers, an interpreter; an actor; a dissembler, pretender, hypocrite." },
        { word: "Bound", definition: "to bind, tie; metaph. Satan is said to bind a woman." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 13:10-17\nTheme: Woman, Thou art Loose from Your Infirmity.",
      questions: [
        "Where did this miracle take place?",
        "What was wrong with the woman in the passage?",
        "How long had the woman been sick?",
        "What did Jesus say to the woman when he saw her?",
        "How did Jesus heal the woman?",
        "How long did it take for the woman to be healed?",
        "Who was upset that Jesus healed on the Sabbath?",
        "What did Jesus say to the ruler of the synagogue?",
        "What did Jesus call the woman?"
      ]
    },
    {
      id: 19,
      chapterId: 7,
      number: 19,
      title: "A Man Healed from Dropsy",
      passage: "Luke 14:2-5",
      additionalPassages: "",
      theme: "A Man Healed from Dropsy.",
      image: "color_14_2_5.jpg",
      scripture: `Luke 14:2-5 — And, behold, there was a certain man before him which had the dropsy. And Jesus answering spake unto the lawyers and Pharisees, saying, Is it lawful to heal on the sabbath day? And they held their peace. And he took him, and healed him, and let him go; And answered them, saying, Which of you shall have an ass or an ox fallen into a pit, and will not straightway pull him out on the sabbath day?`,
      keyTerms: [
        { word: "Dropsy", definition: "suffering from dropsy; dropsy is an accumulation of watery fluid in the body." },
        { word: "Lawyers", definition: "an expert in the Mosaic law; one skilled in the law." },
        { word: "Pharisees", definition: "a sect that seemed to have started after the Jewish exile; separated ones; the dominant religious group of Judaism." },
        { word: "Lawful", definition: "lawful, allowable; what is permitted; what is among the things lawful and right." },
        { word: "Held their peace", definition: "to be silent, hold one's peace; to leave off speaking." },
        { word: "Healed", definition: "to cure, to make whole; to free from errors and sins." },
        { word: "Pit", definition: "a pit, i.e. a hole in the ground; a cistern, used as a prison." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 14:2-5\nTheme: A Man Healed from Dropsy.",
      questions: [
        "Where was Jesus when this miracle took place?",
        "What was wrong with the man in this passage?",
        "What question did Jesus ask the lawyers and Pharisees?",
        "What was the response of the lawyers and Pharisees?",
        "What three things did Jesus do for the man?",
        "What did Jesus say to answer the lawyers and Pharisees?",
        "What does this miracle teach us about Jesus?"
      ]
    },
    {
      id: 20,
      chapterId: 8,
      number: 20,
      title: "Young Man, I Say Unto You Arise",
      passage: "Luke 7:11-17",
      additionalPassages: "",
      theme: "Young man, I say unto you Arise.",
      image: "color_7_11_17.jpg",
      scripture: `Luke 7:11-17 — And it came to pass the day after, that he went into a city called Nain; and many of his disciples went with him, and much people. Now when he came nigh to the gate of the city, behold, there was a dead man carried out, the only son of his mother, and she was a widow: and much people of the city was with her. And when the Lord saw her, he had compassion on her, and said unto her, Weep not. And he came and touched the bier: and they that bare him stood still. And he said, Young man, I say unto thee, Arise. And he that was dead sat up, and began to speak. And he delivered him to his mother. And there came a fear on all: and they glorified God, saying, That a great prophet is risen up among us; and, That God hath visited his people.`,
      keyTerms: [
        { word: "Nain", definition: "a city of Galilee." },
        { word: "Widow", definition: "a widow; bereft of a husband." },
        { word: "Compassion", definition: "to be moved as to one's bowels, hence to be moved with compassion, have compassion for." },
        { word: "Bier", definition: "a stretcher, a bier, a flat surface upon which a corpse was placed." },
        { word: "Arise", definition: "to cause to rise up, raise up; of persons lying down." },
        { word: "Delivered", definition: "to give away for one's own profit; to give back, restore." },
        { word: "Glorified", definition: "to praise, extol, magnify, celebrate." },
        { word: "Prophet", definition: "in Greek writings, an interpreter of oracles or of other hidden things; one who, moved by the Spirit of God, declares to men what he has received by inspiration." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 7:11-17\nTheme: Young man, I say unto you Arise.",
      questions: [
        "What city did Jesus go to in this passage?",
        "Who was being carried out of the city?",
        "What was the relationship of the dead man to his mother?",
        "What was the mother's condition?",
        "What did Jesus say to the mother?",
        "What did Jesus do to the bier?",
        "What did Jesus say to the dead man?",
        "What happened when Jesus spoke to the dead man?",
        "What did Jesus do after the man arose?",
        "What did the people say when they saw this miracle?"
      ]
    },
    {
      id: 21,
      chapterId: 8,
      number: 21,
      title: "Maid, Arise",
      passage: "Luke 8:41-42; 8:49-56",
      additionalPassages: "",
      theme: "Maid, Arise.",
      image: "color_8_41_42.jpg",
      scripture: `Luke 8:41-42; 49-56 — And, behold, there came a man named Jairus, and he was a ruler of the synagogue: and he fell down at Jesus' feet, and besought him that he would come into his house: For he had one only daughter, about twelve years of age, and she lay a dying. While he yet spake, there cometh one from the ruler of the synagogue's house, saying to him, Thy daughter is dead; trouble not the Master. But when Jesus heard it, he answered him, saying, Fear not: believe only, and she shall be made whole. And he suffered no man to go in, save Peter, and James, and John, and the father and the mother of the maiden. And all wept, and bewailed her: but he said, Weep not; she is not dead, but sleepeth. And they laughed him to scorn, knowing that she was dead. And he put them all out, and took her by the hand, and called, saying, Maid arise. And her spirit came again, and she arose straightway: and he commanded to give her meat. And her parents were astonished.`,
      keyTerms: [
        { word: "Jairus", definition: "a ruler of the synagogue; a man whose daughter Jesus raised from the dead." },
        { word: "Ruler", definition: "a chief, leader, ruler; commander, lord." },
        { word: "Besought", definition: "to ask, beg, call for, crave, desire, require." },
        { word: "Trouble", definition: "to crowd, throng; to disturb, trouble." },
        { word: "Fear not", definition: "stop being afraid; do not fear." },
        { word: "Wept", definition: "to weep, wail; of those who mourn for the dead." },
        { word: "Bewailed", definition: "to weep for, mourn for; to weep over the fate of a person." },
        { word: "Sleepeth", definition: "to sleep; metaph. to be dead." },
        { word: "Astonished", definition: "to put out of wits, astound, amaze; to be struck with astonishment, astounded, amazed." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 8:41-42; 8:49-56\nTheme: Maid, Arise.",
      questions: [
        "Who came to Jesus in this passage?",
        "What was Jairus' position?",
        "What did Jairus ask of Jesus?",
        "What was wrong with Jairus' daughter?",
        "What news came while Jesus was on his way?",
        "What did Jesus say to Jairus when he heard the news?",
        "Who did Jesus allow to go with him into the house?",
        "What did Jesus say to the people who were weeping?",
        "What did Jesus say to the girl?",
        "What happened when Jesus spoke to the girl?"
      ]
    },
    {
      id: 22,
      chapterId: 9,
      number: 22,
      title: "Tell What You Have Seen and Heard",
      passage: "Luke 7:18-23",
      additionalPassages: "",
      theme: "Tell what you have seen and heard.",
      image: "color_7_18_23.jpg",
      scripture: `Luke 7:18-23 — And the disciples of John shewed him of all these things. And John calling unto him two of his disciples sent them to Jesus, saying, Art thou he that should come? or look we for another? When the men were come unto him, they said, John Baptist hath sent us unto thee, saying, Art thou he that should come? or look we for another? And in that same hour he cured many of their infirmities and plagues, and of evil spirits; and unto many that were blind he gave sight. Then Jesus answering said unto them, Go your way, and tell John what things ye have seen and heard; how that the blind see, the lame walk, the lepers are cleansed, the deaf hear, the dead are raised, to the poor the gospel is preached. And blessed is he, whosoever shall not be offended in me.`,
      keyTerms: [
        { word: "Disciples", definition: "a learner, pupil, disciple; in the NT it means the followers of Jesus." },
        { word: "Infirmities", definition: "want of strength, weakness, infirmity; feebleness of health or sickness." },
        { word: "Plagues", definition: "a whip; a scourge; of disease; a calamity, a misfortune." },
        { word: "Blind", definition: "sightless; used of those who cannot see." },
        { word: "Lame", definition: "lame, crippled in the feet; halting." },
        { word: "Cleansed", definition: "to make clean, cleanse; to free from guilt of sin, to purify." },
        { word: "Deaf", definition: "deaf; dumb, and deaf; sometimes used of dumb persons." },
        { word: "Blessed", definition: "blessed, happy; of extending God's favor." },
        { word: "Offended", definition: "to put a stumbling block or impediment in the way, upon which another may trip and fall." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 7:18-23\nTheme: Tell what you have seen and heard.",
      questions: [
        "Who told John about the miracles of Jesus?",
        "Who did John send to Jesus?",
        "What did John's disciples ask Jesus?",
        "What was Jesus doing when John's disciples arrived?",
        "What did Jesus tell John's disciples to report back?",
        "List the six miracles that Jesus mentioned.",
        "What did Jesus say about those who would not be offended by him?"
      ]
    },
    {
      id: 23,
      chapterId: 9,
      number: 23,
      title: "Tell That Fox",
      passage: "Luke 13:32-33",
      additionalPassages: "",
      theme: "Tell that Fox.",
      image: "color_13_32_33.jpg",
      scripture: `Luke 13:32-33 — And he said unto them, Go ye, and tell that fox, Behold, I cast out devils, and I do cures to day and to morrow, and the third day I shall be perfected. Nevertheless I must walk to day, and to morrow, and the day following: for it cannot be that a prophet perish out of Jerusalem.`,
      keyTerms: [
        { word: "Fox", definition: "a fox; metaph. a crafty sly man." },
        { word: "Cast out", definition: "to drive out, to expel a person; to banish; to cast out; to send away." },
        { word: "Devils", definition: "evil spirits or the messengers and ministers of the devil." },
        { word: "Cures", definition: "a perfect work; an accomplished result; a healing." },
        { word: "Perfected", definition: "to make perfect, complete; to carry through completely, to accomplish, finish, bring to an end." },
        { word: "Prophet", definition: "a prophet; one moved by the Spirit of God to declare to men what he has received by inspiration." },
        { word: "Perish", definition: "to destroy; to put out of the way entirely, abolish, put an end to ruin." },
        { word: "Jerusalem", definition: "the holy city of the Jews; the capital of Palestine." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 13:32-33\nTheme: Tell that Fox.",
      questions: [
        "Who told Jesus that Herod wanted to kill him?",
        "What did Jesus call Herod?",
        "What two things did Jesus say he was doing?",
        "What did Jesus say would happen on the third day?",
        "What did Jesus say he must do today and tomorrow?",
        "What did Jesus say could not happen outside of Jerusalem?",
        "What does this passage reveal about Jesus' mission?"
      ]
    },
    {
      id: 24,
      chapterId: 10,
      number: 24,
      title: "Teach Us How to Pray",
      passage: "Luke 11:1-4",
      additionalPassages: "",
      theme: "Teach us How to Pray.",
      image: "color_11_1_4.jpg",
      scripture: `Luke 11:1-4 — And it came to pass, that, as he was praying in a certain place, when he ceased, one of his disciples said unto him, Lord, teach us to pray, as John also taught his disciples. And he said unto them, When ye pray, say, Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done, as in heaven, so in earth. Give us day by day our daily bread. And forgive us our sins; for we also forgive every one that is indebted to us. And lead us not into temptation; but deliver us from evil.`,
      keyTerms: [
        { word: "Praying", definition: "to offer prayers, to pray; to pray to God." },
        { word: "Disciples", definition: "a learner, pupil, disciple; the followers of Jesus." },
        { word: "Hallowed", definition: "to render or acknowledge, or to be holy; to separate from profane things and dedicate to God." },
        { word: "Kingdom", definition: "royal power, kingship, dominion, rule; not to be confused with an actual kingdom but rather the right or authority to rule over a kingdom." },
        { word: "Daily bread", definition: "the bread of the coming day or of the following day; necessary for existence; the bread of the present day." },
        { word: "Forgive", definition: "to send away; to release from penalty; to forgive, remit." },
        { word: "Sins", definition: "to be without a share in; to miss the mark; to err, be mistaken; missing the standard." },
        { word: "Temptation", definition: "an experiment, attempt, trial, proving; the trial of man's fidelity, integrity, virtue, constancy." },
        { word: "Deliver", definition: "to draw to oneself; to rescue, to deliver." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:1-4\nTheme: Teach us How to Pray.",
      questions: [
        "What was Jesus doing when the disciple asked him to teach them to pray?",
        "Who else had taught his disciples to pray?",
        "What is the first thing Jesus said to say when you pray?",
        "What does 'Hallowed be thy name' mean?",
        "What did Jesus say about the kingdom in the Lord's Prayer?",
        "What did Jesus say about daily bread in the prayer?",
        "What did Jesus say about forgiveness in the prayer?",
        "What did Jesus say about temptation in the prayer?",
        "What did Jesus say about deliverance in the prayer?"
      ]
    },
    {
      id: 25,
      chapterId: 10,
      number: 25,
      title: "Ask, Seek & Knock",
      passage: "Luke 11:9-13",
      additionalPassages: "",
      theme: "Ask, Seek & Knock.",
      image: "color_11_9_10.jpg",
      scripture: `Luke 11:9-13 — And I say unto you, Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you. For every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened. If a son shall ask bread of any of you that is a father, will he give him a stone? or if he ask a fish, will he for a fish give him a serpent? Or if he shall ask an egg, will he offer him a scorpion? If ye then, being evil, know how to give good gifts unto your children: how much more shall your heavenly Father give the Holy Spirit to them that ask him?`,
      keyTerms: [
        { word: "Ask", definition: "to ask, beg, call for, crave, desire, require." },
        { word: "Seek", definition: "to seek in order to find; to seek a thing; to seek after, seek for, aim at, strive after." },
        { word: "Knock", definition: "to knock at a door." },
        { word: "Receiveth", definition: "to take with the hand, lay hold of, any person or thing in order to use it; to take up a thing to be carried; to take upon one's self." },
        { word: "Findeth", definition: "to come upon, hit upon, to meet with; after searching, to find a thing sought." },
        { word: "Opened", definition: "to open; metaph. to open the mind of one, i.e. to cause to understand a thing." },
        { word: "Father", definition: "generator or male ancestor; metaph. God is called the Father of the stars." },
        { word: "Holy Spirit", definition: "the Spirit of God, the Holy Spirit; the third person of the triune God." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:9-13\nTheme: Ask, Seek & Knock.",
      questions: [
        "What three things did Jesus say to do in prayer?",
        "What did Jesus promise to those who ask?",
        "What did Jesus promise to those who seek?",
        "What did Jesus promise to those who knock?",
        "What example did Jesus use about a father and bread?",
        "What example did Jesus use about a father and a fish?",
        "What example did Jesus use about an egg?",
        "What did Jesus say God would give to those who ask Him?",
        "What does this passage teach us about the nature of God?"
      ]
    },
    {
      id: 26,
      chapterId: 11,
      number: 26,
      title: "Arise and Give",
      passage: "Luke 11:5-8",
      additionalPassages: "",
      theme: "Arise and Give.",
      image: "color_11_5_8.jpg",
      scripture: `Luke 11:5-8 — And he said unto them, Which of you shall have a friend, and shall go unto him at midnight, and say unto him, Friend, lend me three loaves; For a friend of mine in his journey is come to me, and I have nothing to set before him? And he from within shall answer and say, Trouble me not: the door is now shut, and my children are with me in bed; I cannot rise and give thee. I say unto you, Though he will not rise and give him, because he is his friend, yet because of his importunity he will rise and give him as many as he needeth.`,
      keyTerms: [
        { word: "Midnight", definition: "the middle of the night." },
        { word: "Lend", definition: "to lend, to give what is due; to lend freely, give graciously." },
        { word: "Loaves", definition: "food made of flour mixed with water and baked; a loaf of bread." },
        { word: "Journey", definition: "a way, a road, a journey, a march; metaph. a course of conduct." },
        { word: "Trouble", definition: "to crowd, throng, press upon; to disturb, trouble." },
        { word: "Importunity", definition: "shamelessness; a persistence in requesting despite refusal; boldness." },
        { word: "Needeth", definition: "to have need of, need, require; to owe a debt, be in debt." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 11:5-8\nTheme: Arise and Give.",
      questions: [
        "What was the situation described in the parable?",
        "What did the man ask his friend at midnight?",
        "What reason did the man give for refusing to get up?",
        "Why did Jesus say the man would eventually rise and give?",
        "What is importunity?",
        "What does this parable teach us about prayer?",
        "How does this parable relate to our relationship with God in prayer?"
      ]
    },
    {
      id: 27,
      chapterId: 11,
      number: 27,
      title: "God Will Avenge Your Adversary",
      passage: "Luke 18:1-8",
      additionalPassages: "",
      theme: "God will Avenge your Adversary.",
      image: "color_18_1_8.jpg",
      scripture: `Luke 18:1-8 — And he spake a parable unto them to this end, that men ought always to pray, and not to faint; Saying, There was in a city a judge, which feared not God, neither regarded man: And there was a widow in that city; and she came unto him, saying, Avenge me of mine adversary. And he would not for a while: but afterward he said within himself, Though I fear not God, nor regard man; Yet because this widow troubleth me, I will avenge her, lest by her continual coming she weary me. And the Lord said, Hear what the unjust judge saith. And shall not God avenge his own elect, which cry day and night unto him, though he bear long with them? I tell you that he will avenge them speedily. Nevertheless when the Son of man cometh, will he find faith on the earth?`,
      keyTerms: [
        { word: "Parable", definition: "a placing of one thing by the side of another, a comparing; a narrative, fictitious but agreeable to the laws and usages of human life, by which either the duties of men or the things of God are figuratively portrayed." },
        { word: "Faint", definition: "to behave badly; to be remiss; to be exhausted, grow weary, to lose one's spirit." },
        { word: "Judge", definition: "a judge, umpire; an arbitrator." },
        { word: "Widow", definition: "a widow; bereft of a husband." },
        { word: "Avenge", definition: "to protect, defend, avenge, vindicate." },
        { word: "Adversary", definition: "an opponent in a suit at law; an adversary." },
        { word: "Importunity", definition: "persistence; continual coming." },
        { word: "Elect", definition: "chosen out, selected; in the NT, choice, select, i.e. the best of its kind or class, excellence preeminent." },
        { word: "Speedily", definition: "with speed, quickly, speedily." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 18:1-8\nTheme: God will Avenge your Adversary.",
      questions: [
        "What was the purpose of this parable?",
        "What kind of judge was in the city?",
        "What did the widow ask of the judge?",
        "Why did the judge eventually grant the widow's request?",
        "What does the unjust judge represent in this parable?",
        "What did Jesus say God would do for His elect?",
        "How often did Jesus say God's elect should cry unto Him?",
        "What question did Jesus ask at the end of this parable?",
        "What does this parable teach us about persistent prayer?"
      ]
    },
    {
      id: 28,
      chapterId: 11,
      number: 28,
      title: "True Prayers",
      passage: "Luke 18:9-14",
      additionalPassages: "",
      theme: "True Prayers.",
      image: "color_18_9_14.jpg",
      scripture: `Luke 18:9-14 — And he spake this parable unto certain which trusted in themselves that they were righteous, and despised others: Two men went up into the temple to pray; the one a Pharisee, and the other a publican. The Pharisee stood and prayed thus with himself, God, I thank thee, that I am not as other men are, extortioners, unjust, adulterers, or even as this publican. I fast twice in the week, I give tithes of all that I possess. And the publican, standing afar off, would not lift up so much as his eyes unto heaven, but smote his breast, saying, God be merciful to me a sinner. I tell you, this man went down to his house justified rather than the other: for every one that exalteth himself shall be abased; and he that humbleth himself shall be exalted.`,
      keyTerms: [
        { word: "Parable", definition: "a narrative, fictitious but agreeable to the laws and usages of human life, by which either the duties of men or the things of God are figuratively portrayed." },
        { word: "Pharisee", definition: "a sect that seemed to have started after the Jewish exile; separated ones." },
        { word: "Publican", definition: "a tax-gatherer; collector of public taxes." },
        { word: "Extortioners", definition: "a robber; one who seizes what belongs to another; a plunderer." },
        { word: "Tithes", definition: "a tenth part of all that is acquired by man; the tithe." },
        { word: "Merciful", definition: "to be propitious, be gracious, be merciful; to make propitiation for." },
        { word: "Justified", definition: "to render righteous or such he ought to be; to show, exhibit, evince, one to be righteous." },
        { word: "Exalteth", definition: "to lift up on high, to exalt; metaph. to raise to the very summit of opulence and prosperity." },
        { word: "Humbleth", definition: "to make low, bring low; metaph. to bring into a humble condition, reduce to meaner circumstances." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 18:9-14\nTheme: True Prayers.",
      questions: [
        "Who did Jesus tell this parable to?",
        "Who were the two men in this parable?",
        "How did the Pharisee pray?",
        "What did the Pharisee boast about in his prayer?",
        "How did the publican pray?",
        "What did the publican say in his prayer?",
        "Which man went home justified?",
        "What did Jesus say about those who exalt themselves?",
        "What did Jesus say about those who humble themselves?"
      ]
    },
    {
      id: 29,
      chapterId: 12,
      number: 29,
      title: "Jesus Gave the 12 Disciples Power and Authority",
      passage: "Luke 9:1-5",
      additionalPassages: "",
      theme: "Jesus gave the 12 Disciples Power and Authority.",
      image: "color_9_1_5.jpg",
      scripture: `Luke 9:1-5 — Then he called his twelve disciples together, and gave them power and authority over all devils, and to cure diseases. And he sent them to preach the kingdom of God, and to heal the sick. And he said unto them, Take nothing for your journey, neither staves, nor scrip, neither bread, neither money; neither have two coats apiece. And whatsoever house ye enter into, there abide, and thence depart. And whosoever will not receive you, when ye go out of that city, shake off the very dust from your feet for a testimony against them.`,
      keyTerms: [
        { word: "Power", definition: "strength power, ability; inherent power, power residing in a thing by virtue of its nature; power for performing miracles." },
        { word: "Authority", definition: "power of choice, liberty of doing as one pleases; the power of rule or government; the power of judicial decision." },
        { word: "Devils", definition: "evil spirits or the messengers and ministers of the devil." },
        { word: "Cure", definition: "to cure, heal; to make whole; to free from errors and sins, to bring about one's salvation." },
        { word: "Preach", definition: "to be a herald, to officiate as a herald; to proclaim after the manner of a herald." },
        { word: "Kingdom", definition: "royal power, kingship, dominion, rule." },
        { word: "Staves", definition: "a staff; a walking stick; a rod." },
        { word: "Testimony", definition: "in a legal sense, testimony, evidence; a declaration of facts." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 9:1-5\nTheme: Jesus gave the 12 Disciples Power and Authority.",
      questions: [
        "Who did Jesus call together?",
        "What two things did Jesus give to his disciples?",
        "What did Jesus give them power over?",
        "What did Jesus send them to preach?",
        "What did Jesus say to take on their journey?",
        "What did Jesus tell them to do when they entered a house?",
        "What did Jesus tell them to do if people did not receive them?",
        "What does this passage teach us about the authority given to believers?"
      ]
    },
    {
      id: 30,
      chapterId: 12,
      number: 30,
      title: "One Casting Out Devils in Jesus Name",
      passage: "Luke 9:49-50",
      additionalPassages: "",
      theme: "One Casting out Devils in Jesus Name.",
      image: "color_9_49_50.jpg",
      scripture: `Luke 9:49-50 — And John answered and said, Master, we saw one casting out devils in thy name; and we forbad him, because he followeth not with us. And Jesus said unto him, Forbid him not: for he that is not against us is for us.`,
      keyTerms: [
        { word: "Casting out", definition: "to drive out, to expel; to cast out; to send away; to expel a person from society." },
        { word: "Devils", definition: "evil spirits or the messengers and ministers of the devil." },
        { word: "Name", definition: "the name by which a person or a thing is called; metaph. authority, cause." },
        { word: "Forbad", definition: "to forbid, prohibit; to hinder, prevent." },
        { word: "Forbid", definition: "to command one to cease, to stop; to prohibit, prevent." },
        { word: "Against", definition: "over against, opposite to, before; against; in opposition to." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 9:49-50\nTheme: One Casting out Devils in Jesus Name.",
      questions: [
        "What did John tell Jesus he saw?",
        "What did John and the disciples do about this person?",
        "Why did John say they forbade the person?",
        "What did Jesus say in response?",
        "What principle did Jesus establish in this passage?",
        "What does this teach us about casting out devils in Jesus' name?",
        "How does this passage apply to the church today?"
      ]
    },
    {
      id: 31,
      chapterId: 12,
      number: 31,
      title: "I Give You Power",
      passage: "Luke 10:17-20",
      additionalPassages: "",
      theme: "I give you power.",
      image: "color_10_1_4.jpg",
      scripture: `Luke 10:17-20 — And the seventy returned again with joy, saying, Lord, even the devils are subject unto us through thy name. And he said unto them, I beheld Satan as lightning fall from heaven. Behold, I give unto you power to tread on serpents and scorpions, and over all the power of the enemy: and nothing shall by any means hurt you. Notwithstanding in this rejoice not, that the spirits are subject unto you; but rather rejoice, because your names are written in heaven.`,
      keyTerms: [
        { word: "Seventy", definition: "seventy; the number of elders appointed by Moses." },
        { word: "Subject", definition: "to arrange under, to subordinate; to subject, put in subjection." },
        { word: "Satan", definition: "the adversary, the prince of evil spirits; the inveterate adversary of God and Christ." },
        { word: "Lightning", definition: "lightning; the gleam of a lamp or other brilliant light." },
        { word: "Power", definition: "strength, power, ability; power for performing miracles." },
        { word: "Tread", definition: "to tread, trample; to tread under foot." },
        { word: "Serpents", definition: "a snake, serpent; metaph. of a sly, artful man." },
        { word: "Scorpions", definition: "a scorpion; represents the power of evil." },
        { word: "Heaven", definition: "the vaulted expanse of the sky with all things visible in it; metaph. the eternal blessedness of the life after resurrection." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 10:17-20\nTheme: I give you power.",
      questions: [
        "Who returned with joy in this passage?",
        "What were the seventy rejoicing about?",
        "What did Jesus say He beheld?",
        "What power did Jesus give to the seventy?",
        "What did Jesus say nothing would do to them?",
        "What did Jesus tell them not to rejoice about?",
        "What did Jesus tell them to rejoice about?",
        "What does this passage teach us about true spiritual victory?"
      ]
    },
    {
      id: 32,
      chapterId: 12,
      number: 32,
      title: "Showing Mercy Toward Your Neighbor",
      passage: "Luke 10:30-35",
      additionalPassages: "",
      theme: "Showing mercy toward your neighbor.",
      image: "color_10_30_35.jpg",
      scripture: `Luke 10:30-35 — And Jesus answering said, A certain man went down from Jerusalem to Jericho, and fell among thieves, which stripped him of his raiment, and wounded him, and departed, leaving him half dead. And by chance there came down a certain priest that way: and when he saw him, he passed by on the other side. And likewise a Levite, when he was at the place, came and looked on him, and passed by on the other side. But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he had compassion on him, And went to him, and bound up his wounds, pouring in oil and wine, and set him on his own beast, and brought him to an inn, and took care of him. And on the morrow when he departed, he took out two pence, and gave them to the host, and said unto him, Take care of him; and whatsoever thou spendest more, when I come again, I will repay thee.`,
      keyTerms: [
        { word: "Thieves", definition: "a thief; one who takes property by stealth." },
        { word: "Stripped", definition: "to undress, to strip of clothing." },
        { word: "Raiment", definition: "clothing, garments; that with which the body is clothed." },
        { word: "Priest", definition: "one who offers sacrifices and in general is busied with sacred rites." },
        { word: "Levite", definition: "a Levite, one of the tribe of Levi." },
        { word: "Samaritan", definition: "an inhabitant of the city of Samaria; relating to or belonging to Samaria." },
        { word: "Compassion", definition: "to be moved as to one's bowels, hence to be moved with compassion, have compassion for." },
        { word: "Inn", definition: "a place of lodging, an inn." },
        { word: "Repay", definition: "to give away, yield up, deliver; to give back, restore; to recompense." }
      ],
      treasureChestNote: "Read and Take Notes @ Luke 10:30-35\nTheme: Showing mercy toward your neighbor.",
      questions: [
        "Where was the man traveling from and to?",
        "What happened to the man on his journey?",
        "Who was the first to pass by the wounded man?",
        "Who was the second to pass by the wounded man?",
        "Who stopped to help the wounded man?",
        "What did the Samaritan do for the wounded man?",
        "Where did the Samaritan take the wounded man?",
        "What did the Samaritan tell the innkeeper?",
        "Who is our neighbor according to this parable?",
        "What does this parable teach us about showing mercy?"
      ]
    }
  ]
};
